# Generated by Django 5.1.7 on 2025-04-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=200)),
                ('delivery_location', models.CharField(max_length=200)),
                ('goods_type', models.CharField(max_length=100)),
                ('truck_type', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type', models.CharField(max_length=50)),
                ('availability_status', models.CharField(default='Available', max_length=20)),
            ],
        ),
    ]
