# Generated by Django 5.1.7 on 2025-04-15 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=100)),
                ('estimated_delivery_date', models.DateField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.booking')),
            ],
        ),
    ]
