# Generated by Django 5.1.7 on 2025-04-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_booking_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('review_text', models.TextField()),
            ],
        ),
    ]
